name: dbook9
recipe: drupal9
config:
  webroot: backend/web
  php: '8.1'
  composer_version: '2.0.7'
services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        BASE_URL: "http://dbook9.lndo.site"
    build_as_root:
      - echo "####################" excute composer instal ############################""
      - cd /app/backend/web && composer install

tooling:
  composer:
    service: appserver
    dir: /app/backend
  drush:
    service: appserver
    cmd: /app/web/vendor/bin/drush
    env:
      DRUSH_OPTIONS_URI: "http://dbook9.lndo.site/"
